services:
  backend:
    build:
      context: ./backend
    container_name: ecmsbackend
    ports:
      - "9999:9999"

  frontend:
    build:
      context: ./frontend
    container_name: ecmsfrontend
    ports:
      - "3000:3000"
    environment:
      - HOST=0.0.0.0
    depends_on:
      - backend
